site_name: "Lemniscat"
site_url: !!python/object/apply:os.getenv ["SITE_URL"]
theme:
  name: material
  language: en
  #custom_dir: doc/overrides
  palette:
    scheme: slate
    primary: amber
  font:
    text: Poppins
  features:
    - content.code.copy


plugins:
  - search

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

docs_dir: doc/docs

nav:
  - How it is ? : index.md
  - How to install ? : setup.md
  - How to use ? : usage.md
  - How to write a Manifest ? : manifest.md
  - How it' works ? : runtime.md
  - How to use plugins ?:
    - Terraform: plugins/terraform/README.md
    - Powershell: plugins/powershell/README.md
    - AzureCLI: plugins/azurecli/README.md
    - FileTransform: plugins/filetransform/README.md


# extra_css:
#   - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/morisseauphi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pmorisseau