name: github-pages 
on:
  push:
    branches: 
      - feat/init-pages

jobs:
  deploy-ToGithubPages:
    runs-on: ubuntu-latest
    env:
      SITE_URL: "https://lemniscat-devops.github.io/doc/"
    environment: github-pages  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v4
        with:
          repository: lemniscat-devops/lemniscat.plugin.terraform
          token: ${{ secrets.GITHUB_TOKEN }}
          path: lemniscat.plugin.terraform
      - uses: actions/checkout@v4
        with:
          repository: lemniscat-devops/lemniscat.plugin.powershell
          token: ${{ secrets.GITHUB_TOKEN }}
          path: lemniscat.plugin.powershell
      - uses: actions/checkout@v4
        with:
          repository: lemniscat-devops/lemniscat.plugin.azurecli
          token: ${{ secrets.GITHUB_TOKEN }}
          path: lemniscat.plugin.azurecli
      - uses: actions/checkout@v4
        with:
          repository: lemniscat-devops/lemniscat.plugin.filetransform
          token: ${{ secrets.GITHUB_TOKEN }}
          path: lemniscat.plugin.filetransform
      - run: |
          mkdir /home/runner/work/doc/doc/docs/plugins/terraform
          mkdir /home/runner/work/doc/doc/docs/plugins/powershell
          mkdir /home/runner/work/doc/doc/docs/plugins/azurecli
          mkdir /home/runner/work/doc/doc/docs/plugins/filetransform
          cp -r /home/runner/work/doc/doc/lemniscat.plugin.terraform/README.md /home/runner/work/doc/doc/docs/plugins/terraform
          cp -r /home/runner/work/doc/doc/lemniscat.plugin.powershell/README.md /home/runner/work/doc/doc/docs/plugins/powershell
          cp -r /home/runner/work/doc/doc/lemniscat.plugin.azurecli/README.md /home/runner/work/doc/doc/docs/plugins/azurecli
          cp -r /home/runner/work/doc/doc/lemniscat.plugin.filetransform/README.md /home/runner/work/doc/doc/docs/plugins/filetransform
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force